# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ae95c35324e4bec5165de18aede455c7be1261bd95267cefbc0f0c9351996a738e38354d2be252d95cf9ddf02b75ae246afd3c6f45465c0a445359d1eef811

test:
  secret_key_base: db4a2529a487ea28533acf4526193ee594125d1d7b6b61896c186442d5457c6d8d1149a35e3b02dd8c2bcd69e5c466eaa2a918d5cf5c6e53cfe6fb7296b410a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
